#!/bin/bash
# ks347 '12


if [ $# != 2 ]; then
    echo "Usage: $0 SLOTS MACHINES_FILE"
    exit
fi 

NSLOTS=$1
MACHINES=$2

# Check to see if mpd is already running
echo "Checking for existing mpd processes..."
mpdringtest 5 >/dev/null

if [ $? == 0 ]; then
    echo "An existing mpd process was found. Skipping."
else
    echo "No existing mpd processes found. Starting a new one..."
    mpdboot --totalnum=$NSLOTS --file=$MACHINES -1 --maxbranch=32
    echo "mpd started with $NSLOTS slots";
fi
